image: golang:1.20

stages:
    - test

lint:
    stage: test
    script:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
        - golangci-lint run

unit_tests:
    stage: test
    script:
        - go install gotest.tools/gotestsum@v1.11.0
        - gotestsum --junitfile unit-tests.xml --packages="./..." -- -coverprofile coverage.out
        - go tool cover -func coverage.out
        - go tool cover -html coverage.out -o coverage.html
    coverage: /total:\s+\(statements\)\s+(\d+\.\d+)%/
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - coverage.html
        reports:
            junit:
                - 'unit-tests.xml'